export const WORDS = [
    'ABOUT', 'ABOVE', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN', 'AGENT', 'AGREE',
    'ALARM', 'ALBUM', 'ALERT', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG',
    'ANGEL', 'ANGER', 'ANGRY', 'APART', 'APPLE', 'APPLY', 'ARGUE', 'ARRAY', 'ASIDE', 'ASSET',
    'AVOID', 'AWAKE', 'AWARD', 'AWARE', 'BASIC', 'BEACH', 'BEGIN', 'BEING', 'BELOW', 'BLACK',
    'BLANK', 'BLIND', 'BLOCK', 'BLOOD', 'BOARD', 'BOOST', 'BOUND', 'BRAIN', 'BRAND', 'BRAVE',
    'BREAD', 'BREAK', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BUILD', 'BUILT', 'CHAIR',
    'CHART', 'CHASE', 'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CLEAN', 'CLEAR', 'CLICK',
    'CLOSE', 'CLOTH', 'CLOUD', 'COLOR', 'COULD', 'COUNT', 'COURT', 'COVER', 'CRAFT', 'CRASH',
    'CRIME', 'CROSS', 'CROWD', 'DAILY', 'DANCE', 'DEATH', 'DOUBT', 'DOZEN', 'DRAFT', 'DREAM',
    'DRINK', 'DRIVE', 'EARLY', 'EARTH', 'EIGHT', 'EMPTY', 'ENJOY', 'ENTER', 'ERROR', 'EVENT'
];